# Generated by Django 3.2.3 on 2021-06-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20210608_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(choices=[('Home', 'home'), ('Lifestyle', 'lifestyle'), ('Programming', 'programming')], max_length=30),
        ),
    ]
